### ISSUE TITLE
Time series problem into supervised learning problem?

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI-522_nhl-game-predictor#10]
How are you going to transform your time series data to make the features compatible with your supervised learning (decision tree) problems?

For example, are you planning to use create lag features for your predictions?

**Comment by shayne-andrews** [comment]
@adityashrm21 
Yes we are planning to use  lags and moving averages on both features and targets. 

We are thinking we'll have to "throw away" the examples in the first n games of the season if we're using moving averages of length n (they will still feed into the features for future games/examples though). This is to avoid looking back into previous seasons which would be less predictive, and also allows us to separate out 1 season for test data that does not "look back" into any of the training data.

@aimirza @ttimbers - Can you see any issues with us going forward on this basis and would you recommend any changes to our approach?

Thanks!

**Comment by shayne-andrews** [comment]
After speaking with Tiffany in lab we think this is a good prediction problem to continue on.
