### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI-522_nhl-game-predictor#27]
@shayne-andrews and @adityashrm21, great job on Milestone 2! Here are some remaining issues:

- [x] Include instructions on how to run your analysis with make on the main readme

**Suggestions:**

- Go through http://swcarpentry.github.io/make-novice/reference. This would help you make your Make code more practical. For example, you can use automatic variables and avoid some repetition.

**Comment by adityashrm21** [comment]
addressed in b15f95

**Comment by adityashrm21** [comment]
We kept the repetition of the variables in the makefile in order to keep things explicit and clear as Tiffany mentioned during the lecture but will change it in future definitely! Thanks for the suggestion!
